name: CI/CD Pipeline

on: 
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Compile TypeScript
      run: npm run compile

    - name: Run unit tests (without VS Code)
      run: npm run test:unit
      env:
        TEST_OPENAI_API_KEY: ${{ secrets.TEST_OPENAI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.TEST_OPENAI_API_KEY }}
        CHANGELOGGER_OPENAI_API_KEY: ${{ secrets.TEST_OPENAI_API_KEY }}

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build extension package
      run: npm run package

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-build-${{ github.sha }}
        path: dist/
        retention-days: 30

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup Xvfb (for VS Code tests)
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Run VS Code Extension Tests
      run: xvfb-run -a npm test
      env:
        TEST_OPENAI_API_KEY: ${{ secrets.TEST_OPENAI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.TEST_OPENAI_API_KEY }}
        CHANGELOGGER_OPENAI_API_KEY: ${{ secrets.TEST_OPENAI_API_KEY }}
        DISPLAY: :99
